### PR TITLE
Improve PCR & RDT Screen

### PR DESCRIPTION
**Pull request by anandarh**
- Improve PCR & RDT Screen
- Improve Custom Bubble Tab
- Improve Announcement Card

Related Task:
[[S15 App] UI halaman Total Pemeriksaan COVID-19](https://trello.com/c/bIMTUei2)

### CODE REVIEW

**Review by jaluowen — APPROVED** [review]

**Review by gaganugraha33 — APPROVED** [review]

**Comment by gaganugraha33** [comment]
conflict gan pr nya @anandarh

**Comment by anandarh** [comment]
> conflict gan pr nya @anandarh

Wait gan haha

**Comment by anandarh** [comment]
> conflict gan pr nya @anandarh

Aman gan @gaganugraha33

**Comment by gaganugraha33** [comment]
eh iya deng wkwk tadi conflict apa yak ga bisa di merge, sip2 gan @anandarh

**Review by gaganugraha33 — APPROVED** [review]

**Pull request merged**
